---
id: dokku-201506
base_name: dokku-201506
tags:
- dokku
presentation_date: 2015.6.20
version: 1.0.0
licenses: []
slideshare_id:
speaker_deck_id:
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :rd
  name: Kazuhiro NISHIYAMA
  email: zn@mbf.nifty.com
  rubygems_user: znz
  slideshare_user: znzjp
  speaker_deck_user: znz
